# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database_gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x61tabase_gateway.proto\x12\nexperiment\x1a\x1bgoogle/protobuf/empty.proto\";\n\x11TemperatureRecord\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\"/\n\x16QueryOutOfRangeRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\"N\n\x17QueryOutOfRangeResponse\x12\x33\n\x0ctemperatures\x18\x01 \x03(\x0b\x32\x1d.experiment.TemperatureRecord\"b\n\x17QueryTemperatureRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x18\n\x10start_epoch_time\x18\x02 \x01(\x01\x12\x16\n\x0e\x65nd_epoch_time\x18\x03 \x01(\x01\"O\n\x18QueryTemperatureResponse\x12\x33\n\x0ctemperatures\x18\x01 \x03(\x0b\x32\x1d.experiment.TemperatureRecord\"m\n\x15\x41\x64\x64TemperatureRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x15\n\rout_of_bounds\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x32\x9a\x02\n\x10\x44\x42GatewayService\x12Z\n\x0fQueryOutOfRange\x12\".experiment.QueryOutOfRangeRequest\x1a#.experiment.QueryOutOfRangeResponse\x12]\n\x10QueryTemperature\x12#.experiment.QueryTemperatureRequest\x1a$.experiment.QueryTemperatureResponse\x12K\n\x0e\x41\x64\x64Temperature\x12!.experiment.AddTemperatureRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_gateway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEMPERATURERECORD']._serialized_start=67
  _globals['_TEMPERATURERECORD']._serialized_end=126
  _globals['_QUERYOUTOFRANGEREQUEST']._serialized_start=128
  _globals['_QUERYOUTOFRANGEREQUEST']._serialized_end=175
  _globals['_QUERYOUTOFRANGERESPONSE']._serialized_start=177
  _globals['_QUERYOUTOFRANGERESPONSE']._serialized_end=255
  _globals['_QUERYTEMPERATUREREQUEST']._serialized_start=257
  _globals['_QUERYTEMPERATUREREQUEST']._serialized_end=355
  _globals['_QUERYTEMPERATURERESPONSE']._serialized_start=357
  _globals['_QUERYTEMPERATURERESPONSE']._serialized_end=436
  _globals['_ADDTEMPERATUREREQUEST']._serialized_start=438
  _globals['_ADDTEMPERATUREREQUEST']._serialized_end=547
  _globals['_DBGATEWAYSERVICE']._serialized_start=550
  _globals['_DBGATEWAYSERVICE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
