# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0enotifier.proto\x1a\x1bgoogle/protobuf/empty.proto"\x84\x01\n\x0fNotifierRequest\x12\x19\n\x11notification_type\x18\x01 \x01(\t\x12\x12\n\nresearcher\x18\x02 \x01(\t\x12\x16\n\x0emeasurement_id\x18\x03 \x01(\t\x12\x15\n\rexperiment_id\x18\x04 \x01(\t\x12\x13\n\x0b\x63ipher_data\x18\x05 \x01(\t2O\n\x0fNotifierService\x12<\n\x10SendNotification\x12\x10.NotifierRequest\x1a\x16.google.protobuf.Emptyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "notifier_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_NOTIFIERREQUEST"]._serialized_start = 48
    _globals["_NOTIFIERREQUEST"]._serialized_end = 180
    _globals["_NOTIFIERSERVICE"]._serialized_start = 182
    _globals["_NOTIFIERSERVICE"]._serialized_end = 261
# @@protoc_insertion_point(module_scope)
