# Consumer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: consumer-img
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: auth-volume
              mountPath: /app/auth
      volumes:
        - name: auth-volume
          secret:
            secretName: auth

---
# Database Gateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-gateway
  template:
    metadata:
      labels:
        app: database-gateway
    spec:
      containers:
        - name: database-gateway
          image: database-gateway-img
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
---
# Notifier Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: notifier-img
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: auth-volume
              mountPath: /app/auth
          ports:
            - containerPort: 50051
      volumes:
        - name: auth-volume
          secret:
            secretName: auth

---
# Rest API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: rest-api-img
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003

---
# Mongo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.6
          imagePullPolicy: IfNotPresent
          args:
            - "--dbpath"
            - "/mnt/tmpfs"
          volumeMounts:
            - name: tmpfs-volume
              mountPath: /mnt/tmpfs
      volumes:
        - name: tmpfs-volume
          emptyDir:
            medium: Memory

---
apiVersion: v1
kind: Service
metadata:
  name: rest-api
spec:
  type: NodePort
  selector:
    app: rest-api
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30674


---
apiVersion: v1
kind: Service
metadata:
  name: database-gateway
spec:
  selector:
    app: database-gateway
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: notifier
spec:
  selector:
    app: notifier
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
