FROM python:3.11-slim-bookworm

COPY notifier/requirements.txt ./
RUN pip install -r requirements.txt

WORKDIR /app

ENV PYTHONPATH=/app

COPY notifier/client_test.py ./client_test.py
COPY proto ./proto

ENTRYPOINT ["python", "client_test.py" ]
